// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMod(arg1, arg2) {
  return window['go']['main']['App']['AddMod'](arg1, arg2);
}

export function GetGameDir() {
  return window['go']['main']['App']['GetGameDir']();
}

export function GetMods() {
  return window['go']['main']['App']['GetMods']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RemoveMod(arg1) {
  return window['go']['main']['App']['RemoveMod'](arg1);
}

export function SetGameDir(arg1) {
  return window['go']['main']['App']['SetGameDir'](arg1);
}
