// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddMod(arg1:string,arg2:string):Promise<void>;

export function GetGameDir():Promise<string>;

export function GetMods():Promise<Array<config.ModConfig>>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function RemoveMod(arg1:string):Promise<void>;

export function SetGameDir(arg1:string):Promise<void>;
